#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  app compile bundler
  mkdir -p "$shome/bin"
  ln -nfs "../vendor/bundle/bin/package_cloud" "$shome/bin/"
}

bootstrap
