#!/usr/bin/env bash

function bootstrap {
  local shome="${_packagecloud_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile bundler --local
  mkdir -p "$shome/bin"
  ln -nfs "../vendor/bundle/bin/package_cloud" "$shome/bin/"
}

bootstrap
